# Ensure packages are installed
- name: "{{ app_name }} action: '{{ app_action }}'"
  ansible.builtin.command:
    cmd: "pkg install {{ item.name }}"
    creates: "/data/data/com.termux/files/usr/bin/{{ item.bin | default(item.name) }}"
  loop:
  - { name: ripgrep, bin: rg }
  - name: fd
  - name: fzf
