---
- name: "termux action: '{{ termux_action }}' - ensure dir"
  ansible.builtin.file:
    path: "$HOME/.termux"
    state: directory
    mode: '0700'

- name: "termux action: '{{ termux_action }}'"
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "$HOME/.termux/{{ item }}"
    mode: '0600'
  loop:
    - 'termux.properties'
    - 'colors.properties'
