- name: "{{ app_name }} action: '{{ app_action }}'"
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ app_name }}-{{ app_action }}"
    block: |
      EDITOR=vim
