---
# Linux terminal configuration based on personal preferences
- hosts: localhost
  gather_facts: false
  roles:
    # bashrc
    - { role: bashrc, tags: [bashrc,ps1],     bashrc_action: PS1 }
    - { role: bashrc, tags: [bashrc,history], bashrc_action: history }
    - { role: bashrc, tags: [bashrc,editor] , bashrc_action: editor }
    # Vim
    - { role: vim,    tags: [vim,spell],      vim_action: spell }
    - { role: vim,    tags: [vim,vimrc],      vim_action: vimrc }
