---
# Linux terminal configuration based on personal preferences
- hosts: localhost
  gather_facts: false
  roles:
    - { role: git,      tags: [git],      app_actions: [packages] }
    - { role: termux,   tags: [termux],   termux_action: conf }
    - { role: bash,     tags: [bash],     app_actions: [packages,PS1,history,editor] }
    - { role: vim,      tags: [vim],      vim_action: spell }
    - { role: vim,      tags: [vim],      vim_action: vimrc }
    - { role: tmux,     tags: [tmux],     tmux_action: packages }
    - { role: tmux,     tags: [tmux],     tmux_action: plugins }
    - { role: tmux,     tags: [tmux],     tmux_action: conf }
    - { role: python,   tags: [python],   python_action: conf }
    - { role: python,   tags: [python],   python_action: packages }
#   - { role: newsboat, tags: [newsboat], newsboat_action: conf }
    - { role: zoxide,   tags: [zoxide],   app_action: packages }
    - { role: zoxide,   tags: [zoxide],   app_action: conf }
