baseURL = 'https://mamut3d.github.io'
languageCode = 'en-us'
title = 'Hope Harder'
theme = 'relearn'
[params]
  # Change default color scheme with a variant one.
    themeVariant = [ "relearn-dark", "relearn-light" ]
